In [2]:
# 주피터노트북 셀 스타일 조절
from IPython.core.display import display, HTML
# display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

# 경고메시지 숨기기
# import warnings
# warnings.filterwarnings(action='ignore')

C:\Users\User\AppData\Local\Temp\ipykernel_22608\1245359941.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


# Numpy 개요

In [3]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
a = np.array(0)

In [4]:
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [5]:
a = np.array(([2,4,6]))
a, a.ndim, type(a) #1차원

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = np.array( [[1,2,3], [4,5,6]] )
a, a.ndim, type(a) # 2차원

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [7]:
a = np.array( [ [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]] ] )
a, a.ndim, type(a) #아래의 리스트가 입체적으로 생각했을 때는 뒤에 붙어 있음 # 3차원

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [8]:
a.shape #(깊이, 행, 열)

(2, 2, 3)

In [9]:
a = np.array(3)
a, a.shape # 행렬아님, 숫자 1개만 있을 경우에는 아님

(array(3), ())

In [10]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape # 5행

(array([1, 3, 5, 7, 9]), (5,))

In [11]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape #2행 3열

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [12]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [14]:
# size는 요소의 수
a= np.array([1, 3, 5, 7, 9])
a.size

5

In [15]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

In [16]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [19]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape} 구조타입={type(myArr.shape)}, size={myArr.size}, 길이={len(myArr)}') #1차원, 구조는 5행, 구조타입은 튜플, 사이즈는 5, len도 5 1차원이라 똑같이 나옴

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,) 구조타입=<class 'tuple'>, size=5, 길이=5


In [20]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [23]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape} 구조타입 = {type(myArr2.shape)}, size = {myArr2.size}, 길이={len(myArr2)}')
#size는 요소의 수 9개, 길이는 행의 갯수 3개 출력

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3) 구조타입 = <class 'tuple'>, size = 9, 길이=3


In [24]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4 ],[10,20 ,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [25]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape} 구조타입 = {type(myArr21.shape)}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

# 넘파이 배열과 리스트와의 차이점
배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [26]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [27]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2) #각각의 요소마다 계산이 들어감, 요소별 연산(element-wise)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [29]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


# dytype

In [2]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [5]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [6]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


In [7]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\User\AppData\Local\Temp\ipykernel_7296\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\User\AppData\Local\Temp\ipykernel_7296\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [8]:
np.log(0)

C:\Users\User\AppData\Local\Temp\ipykernel_7296\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [9]:
np.exp(-np.inf)

0.0

In [10]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [11]:
np.mean(x)  # 평균

4.8076923076923075

In [12]:
np.var(x)  # 분산

115.23224852071006

In [13]:
np.std(x)  # 표준 편차

10.734628476137871

In [14]:
np.max(x)  # 최댓값

23

In [15]:
np.min(x)  # 최소값

-24

In [16]:
np.median(x)  # 중앙값

5.0

In [17]:
np.percentile(x, 0)  # 최소값

-24.0

In [18]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [19]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [20]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [21]:
np.percentile(x, 100)  # 최댓값

23.0

In [22]:
# 넘파이 함수로 배열을 만들때에는 디폴트가 실수(float)형
print(np.ones(10), np.ones(10).dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [23]:
print(np.ones((2,4)), np.ones((2,4)).dtype) #2행4열

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [24]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype) #정수지정

[1 1 1 1 1 1 1 1 1 1] int32


In [25]:
print(np.zeros(10), np.zeros(10).dtype) #불필요한 정보를 날려버리기 위해서 만듦, 또는 무의미한 공간을 채울때

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [26]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [27]:
# 메모리가 비어있음
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int)) #empty일 경우 메모리에 할당된 값을 출력

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[      0       1       0]
 [5570652    1056       0]
 [    768     528     114]]


In [28]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [29]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [30]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [31]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5) #선형 구간 # 시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [32]:
np.logspace(0.1, 1, 10) #로그 구간

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [33]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [34]:
arr = arr.reshape(10,5) #10행 5열로 바꿔주세요
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [35]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [36]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [37]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [38]:
print(np.arange(2,101,2).reshape(5,10))

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


In [39]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1) #행,열 하나만 알아도 -1로 하면 구성해준다.
arr4, arr4.ndim, arr4.shape #괄호가 2개!라 2차원

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [40]:
arr4 = np.arange(1, 31).reshape(1, -1) #행,열 하나만 알아도 -1로 하면 구성해준다.
arr4, arr4.ndim, arr4.shape #괄호가 2개!라 2차원

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 2,
 (1, 30))

In [42]:
a = np.arange(1,21).reshape(5,4) #5행 4열
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 2,
 (5, 4))

In [44]:
a.reshape(-1,5) #5열로 바꿔주세요

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [48]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

In [49]:
a.shape = -1, 3
a, a.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 (4, 3))

In [51]:
a.shape = 2, -1
a, a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [52]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [53]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [54]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [55]:
# 문자열형, 3행 3열 -> 불가
#바꾸는 방식 따로 있다!!!
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

In [56]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [57]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [58]:
# 불린 -> 정수
matrix2.astype(int)

array([1, 0, 1, 1])

In [59]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [60]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [61]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [62]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

In [63]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [64]:
a[0]

1

In [65]:
a[2]

5

In [66]:
a[4]

9

In [67]:
a[-1]

9

In [68]:
a[-3]

5

In [69]:
a[-5]

1

In [70]:
a[[0,2,4]] #여러개 한번에 뽑기도 가능

array([1, 5, 9])

In [72]:
a

array([1, 3, 5, 7, 9])

In [73]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array([[1,3], [4,2]])
b

array([[1, 3],
       [4, 2]])

In [74]:
a[b] #인덱싱값으로 입력됨 #행렬로 들어와서 행렬로 반환해줌
#[a[1], a[3]]
#[a[4], a[2]]

array([[3, 7],
       [9, 5]])

In [75]:
#값 수정도 가능
a[2]=0
a

array([1, 3, 0, 7, 9])

In [76]:
a[1]+=2
a

array([1, 5, 0, 7, 9])

In [77]:
a[0] *= 6
a

array([6, 5, 0, 7, 9])

In [78]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [79]:
#2차원 인덱싱할떄, 값을 하나만 넣으면 행 인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [80]:
a[1]

array([5, 6, 7, 8, 9])

In [81]:
a[2]

array([10, 11, 12, 13, 14])

In [82]:
a[-1]

array([10, 11, 12, 13, 14])

In [83]:
a[-2]

array([5, 6, 7, 8, 9])

In [84]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
#값이 2개 들어가면, 행 열 인덱싱
a[0, 0] #0번째 행의 0번째 열

0

In [87]:
a[0, 1]

1

In [88]:
a[0,2]

2

In [89]:
a[1,0]

5

In [90]:
a[1,2]

7

In [91]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
a[1] = [1,3,5,7,9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [93]:
a[-1] = [10, 10, 10, 10, 10] #or a[-1]=[10]도 가능
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [94]:
a[0] += [1,2,3,4,5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [95]:
matrix_a = np.arange(10)
matrix_b = np.arange(12).reshape(3,4)

matrix_a, matrix_b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [96]:
# 1차원에서 첫 요소와 마지막 요소
matrix_a[0], matrix_a[-1]

(0, 9)

In [97]:
# 2차원에서 1번째행 1번째열
matrix_b[0, 0]

0

In [98]:
matrix_b[0][0] #1차원에서 1차원으로 추출

0

In [99]:
matrix_b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
matrix_b[-1][-1]

11

In [101]:
matrix_b[2][0] = 100
matrix_b

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [100,   9,  10,  11]])

In [102]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [103]:
a[:]

array([1, 3, 5, 7, 9])

In [104]:
 a[1:]

array([3, 5, 7, 9])

In [105]:
a[-1:]

array([9])

In [106]:
a[:3]

array([1, 3, 5])

In [107]:
a[:-1]

array([1, 3, 5, 7])

In [108]:
a[1:4]

array([3, 5, 7])

In [109]:
a[1:-1]

array([3, 5, 7])

In [110]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a[::2]

array([0, 2, 4, 6, 8])

In [112]:
a[::5]

array([0, 5])

In [113]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [114]:
#홀수
a[1::2]

array([1, 3, 5, 7, 9])

In [115]:
a[:-2:2]

array([0, 2, 4, 6])

In [116]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [117]:
a[:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [119]:
a[3:] #값이 비었다

array([], shape=(0, 5), dtype=int32)

In [121]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [122]:
a[-3:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [123]:
a[:0] #빈값

array([], shape=(0, 5), dtype=int32)

In [124]:
a[1:-1]

array([[15, 16, 17, 18, 19]])

In [125]:
a[:, :] #[행의 범위, 열의 범위]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [126]:
a[:, 1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [127]:
a[:, 3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [128]:
a[:, -1:]

array([[14],
       [19],
       [24]])

In [130]:
a[:, -4:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [133]:
a[:, :1]

array([[10],
       [15],
       [20]])

In [134]:
a[:, :5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [135]:
a[:, :-1]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [136]:
a[:, 0:1]

array([[10],
       [15],
       [20]])

In [137]:
a[:, 2:3]

array([[12],
       [17],
       [22]])

In [138]:
a[:, 1:-1]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [139]:
a = np.arange(10, 100).reshape(9, 10)
a

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
a[2:5, :]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [141]:
a[:, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [142]:
a[2:5, 2:5]

array([[32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

In [143]:
a[::2, ::2]

array([[10, 12, 14, 16, 18],
       [30, 32, 34, 36, 38],
       [50, 52, 54, 56, 58],
       [70, 72, 74, 76, 78],
       [90, 92, 94, 96, 98]])

In [144]:
a[::-1, ::-1] #모든게 뒤집어짐

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [145]:
matrix_c = np.arange(1, 26).reshape(5,5)
matrix_c, type(matrix_c), matrix_c.ndim

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 numpy.ndarray,
 2)

# 전치행렬
행의 위치가 열로 바뀜

In [146]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
# 2행 3열로 변환
print(matrix_d.T) #Transpose

[[1 3 5]
 [2 4 6]]


In [149]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3))
#reshape는 flatten으로 숫자를 일렬로 나열하고 그다음 구조를 바꿈

[[1 2 3]
 [4 5 6]]


In [150]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10) #숫자 start, 숫자 end, 출력할 숫자 갯수

array([3, 6, 4, 3, 6, 7, 7, 1, 8, 7])

In [151]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

array([[9, 3, 3, 9, 3],
       [3, 9, 7, 2, 3]])

In [152]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
np.random.shuffle(matrix_e)
matrix_e

array([ 7, 10,  9,  2,  6,  1,  3,  5,  8,  4])

In [156]:
#1-45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호 완성하기
a = np.arange(1,46)
np.random.shuffle(a)
a[:6]

array([45, 44, 35, 11, 38, 23])

In [157]:
np.random.randint(1,46,6)

array([ 4, 11,  2, 24, 29, 36])

In [158]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-0.12878276, -0.28910138,  0.01196038,  1.9553595 ,  1.97629198,
        0.1088129 ,  1.0988607 , -1.58563455, -0.37142885,  0.74924723])

In [159]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[-0.60757791,  0.08435567, -2.22027091, -1.60399137],
       [-0.73937478, -0.35357027,  0.32803307,  2.03957004],
       [ 0.65541199, -2.04770535,  2.41855095,  0.19345028],
       [-0.79567115, -0.22370892, -0.85745466,  0.3911986 ]])

In [160]:
matrix1.max(), matrix1.min()

(1.9762919806475931, -1.5856345476074938)

In [161]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[26, 10, 42, 34, 37],
       [13, 15, 22, 10, 37],
       [48,  7, 42, 29, 36],
       [42, 24,  5, 49, 20],
       [13, 44, 40, 12, 25]])

In [162]:
#어느 방향으로 무엇을 계산할 건지 알려줘야 한다.
np.sum(m1, axis=0) # (x)행 합계

array([142, 100, 151, 134, 155])

In [163]:
np.sum(m1, axis=1) # 열(y) 합계

array([149,  97, 162, 140, 134])

In [164]:
np.sum(m1[0])

149

In [176]:
np.sum(m1[0], axis=0)

149

In [168]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

149

In [169]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[14, 33, 23],
       [34, 13,  1],
       [ 1, 44, 48],
       [ 4, 44, 12]])

In [170]:
np.sort(m2) #행안에서 오름차순으로 열정렬

array([[14, 23, 33],
       [ 1, 13, 34],
       [ 1, 44, 48],
       [ 4, 12, 44]])

In [171]:
np.sort(m2, axis=0) # 행방향 오름차순(요소별로)

array([[ 1, 13,  1],
       [ 4, 33, 12],
       [14, 44, 23],
       [34, 44, 48]])

In [172]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[ 4, 44, 12],
       [ 1, 44, 48],
       [34, 13,  1],
       [14, 33, 23]])

In [173]:
np.sort(m2, axis=1)

array([[14, 23, 33],
       [ 1, 13, 34],
       [ 1, 44, 48],
       [ 4, 12, 44]])

In [174]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값
# 4 5 9 순으로 정렬되는데 인덱스 값이 2 1 0

array([2, 1, 0], dtype=int64)

In [175]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

array([4, 5, 9])

In [5]:
m3 = np.arange(1,11)
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.insert(m3, 0, 100)

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [7]:
m3[-1]

10

In [8]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 500,  10])

In [12]:
np.insert(m3, len(m3), 500)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 500])

In [9]:
m4 = np.arange(1,10).reshape(3,3)
m4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [11]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

array([[100,   1,   2,   3],
       [100,   4,   5,   6],
       [100,   7,   8,   9]])

In [13]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)

array([[100,   1,   2,   3],
       [200,   4,   5,   6],
       [300,   7,   8,   9]])

In [17]:
m4.shape

(3, 3)

In [14]:
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [15]:
# 마지막 컬럼으로 삽입
# 배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1], [100,200,300], axis=1)

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,   8,   9, 300]])

In [18]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [100, 200, 300]])

In [19]:
np.delete(m4, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [22]:
c = np.array([[1,2,3]]) # 2차원
c, c.ndim, c.shape

(array([[1, 2, 3]]), 2, (1, 3))

In [23]:
d = np.array([[4,5,6]]) # 2차원
d, d.ndim, d.shape

(array([[4, 5, 6]]), 2, (1, 3))

In [24]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [25]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, (1, 6))

In [26]:
matrix = np.arange(1, 21)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
matrix > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [28]:
matrix[matrix > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
(matrix > 10).sum() #요소 갯수의 합이 나옴

10

In [35]:
# Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라
m = np.arange(1,101)
np.random.shuffle(m)
m1 = m[:30]
m1

array([ 7, 79, 72, 12, 13, 78, 17, 27, 92, 97, 25, 46, 48, 60, 50, 30, 90,
       52, 58, 31, 93, 85, 18, 63, 29, 54, 10, 44, 82, 56])

In [48]:
m2 = (m1>30) & (m1<70)
m2

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True, False,  True])

In [49]:
m1[m2]

array([46, 48, 60, 50, 52, 58, 31, 63, 54, 44, 56])

In [50]:
#answer
num = np.random.randint(1,100,30)
(num > 30) & (num < 70)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True, False, False, False,  True, False, False,  True, False,
        True, False,  True])

In [51]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

(array([80, 90, 15, 88, 91, 86, 18, 63,  5,  3, 94, 26, 52, 19, 22, 41, 19,
        62, 20,  8, 96, 67, 66, 31, 37, 65, 28, 56,  8, 83]),
 array([63, 52, 41, 62, 67, 66, 31, 37, 65, 56]))

In [52]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([15, 18,  5,  3, 26, 19, 22, 19, 20,  8, 28,  8])

In [53]:
# 10보다 작거나 90보다 큰 수,
num[(num < 10) | (num > 90)]

array([91,  5,  3, 94,  8, 96,  8])

In [54]:
 num[~(num < 10) | (num > 90)]

array([80, 90, 15, 88, 91, 86, 18, 63, 94, 26, 52, 19, 22, 41, 19, 62, 20,
       96, 67, 66, 31, 37, 65, 28, 56, 83])

In [55]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

(array([ 6,  2, 81,  4, 13, 50, 64, 91, 10, 36,  5, 59, 62, 74, 78,  6, 36,
        65, 22,  4, 78,  8, 65, 85, 46, 23, 64, 15, 95, 51]),
 array([ 6, 81,  4,  5, 78]))

# np.where()
np.where(조건식) : 조건식 만족하는 인덱스 반환
np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [56]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90]))

In [57]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 (array([0, 1, 2, 3, 4], dtype=int64),))

array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])